export const TEMPLATE_CODES = [
  'APPOINTMENT_CONFIRMED',
  'APPOINTMENT_REMINDER',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_RESCHEDULED',
  'WORK_ORDER_COMPLETED',
  'CANCELLATION_REQUEST_NEW',
  'LOW_STOCK',
  'OWNER_DIGEST_DAILY',
  'USER_REGISTERED',
  'INVITATION_ISSUED',
] as const;

export type TemplateCode = (typeof TEMPLATE_CODES)[number];
