import { CLOCK, ID_GENERATOR } from '@det/backend-shared-ddd';

export const BRANCH_REPOSITORY = Symbol('BRANCH_REPOSITORY');
export const BAY_REPOSITORY = Symbol('BAY_REPOSITORY');
export const BRANCH_SCHEDULE_REPOSITORY = Symbol('BRANCH_SCHEDULE_REPOSITORY');
export const MASTER_SCHEDULE_REPOSITORY = Symbol('MASTER_SCHEDULE_REPOSITORY');
export const APPOINTMENT_REPOSITORY = Symbol('APPOINTMENT_REPOSITORY');

export const BRANCH_READ_PORT = Symbol('BRANCH_READ_PORT');
export const BAY_READ_PORT = Symbol('BAY_READ_PORT');
export const BRANCH_SCHEDULE_READ_PORT = Symbol('BRANCH_SCHEDULE_READ_PORT');
export const MASTER_SCHEDULE_READ_PORT = Symbol('MASTER_SCHEDULE_READ_PORT');
export const APPOINTMENT_READ_PORT = Symbol('APPOINTMENT_READ_PORT');

export const BRANCH_USAGE_PORT = Symbol('BRANCH_USAGE_PORT');
export const BAY_USAGE_PORT = Symbol('BAY_USAGE_PORT');
export const IAM_USER_PORT = Symbol('IAM_USER_PORT');
export const CATALOG_SERVICE_PORT = Symbol('CATALOG_SERVICE_PORT');
export const CRM_VEHICLE_PORT = Symbol('CRM_VEHICLE_PORT');
export const WORK_ORDER_PORT = Symbol('WORK_ORDER_PORT');
export const SCHEDULING_APPOINTMENT_PORT = Symbol('SCHEDULING_APPOINTMENT_PORT');

export { CLOCK, ID_GENERATOR };
