import { queryConfig, type QueryConfig } from '@det/backend-shared-querying';

const CATALOG_SERVICE_QUERY: QueryConfig = queryConfig()
  .field('id')
  .string()
  .filterable()
  .labelKey('catalog.service.id')
  .field('name')
  .string()
  .searchOperators()
  .filterable()
  .sortable()
  .labelKey('catalog.service.name')
  .field('categoryId')
  .string()
  .filterable()
  .sortable()
  .labelKey('catalog.service.categoryId')
  .field('isActive')
  .boolean()
  .filterable()
  .sortable()
  .labelKey('catalog.service.isActive')
  .field('durationMinutes')
  .number()
  .filterable()
  .sortable()
  .labelKey('catalog.service.durationMinutes')
  .field('pricingType')
  .string()
  .filterable()
  .sortable()
  .labelKey('catalog.service.pricingType')
  .field('displayOrder')
  .number()
  .filterable()
  .sortable()
  .labelKey('catalog.service.displayOrder')
  .field('createdAt')
  .date()
  .filterable()
  .sortable()
  .labelKey('catalog.service.createdAt')
  .field('updatedAt')
  .date()
  .filterable()
  .sortable()
  .labelKey('catalog.service.updatedAt')
  .defaultPageSize(25)
  .maxPageSize(100)
  .defaultSorts('displayOrder,name')
  .maxConditions(20)
  .maxSorts(5)
  .build();

export const CATALOG_SERVICE_DYNAMIC_QUERY_CONFIG = CATALOG_SERVICE_QUERY.parserConfig;
export const CATALOG_SERVICE_QUERY_CAPABILITIES = CATALOG_SERVICE_QUERY.capabilities;
